name: CI/CD Pipeline

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    env:
      NPM_TOKEN: ${{ secrets.NPM_TOKEN }}

    steps:
    - uses: actions/checkout@v4

    - name: Set up Node.js with npm auth
      uses: actions/setup-node@v4
      with:
        node-version: '20.x'
        registry-url: 'https://registry.npmjs.org/'
        always-auth: true
        token: ${{ secrets.NPM_TOKEN }}

    - name: Install dependencies
      run: npm install

    - name: Run the app
      run: node app.js
