name: Health Check on PR

on:
  pull_request:
    branches:
      - main

jobs:
  health-check:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - uses: actions/setup-node@v4
      with:
        node-version: '20.x'

    - run: npm install

    - name: Start server in background
      run: |
        node server.js &
        sleep 3

    - name: Run health check
      run: |
        chmod +x test.sh
        ./test.sh

    - name: Stop server
      run: pkill -f "node server.js" || true
