name: Release to Production

on:
  push:
    tags:
      - stg-stable

permissions:
  contents: write

jobs:
  create-release-branch:
    name: Create Release Branch
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
      with:
        fetch-depth: 0

    - name: Create release branch from stg-stable
      run: |
        git fetch origin tag stg-stable
        RELEASE_BRANCH="release/$(date +'%d%m%Y')"
        git checkout -b $RELEASE_BRANCH stg-stable
        git push origin $RELEASE_BRANCH
        echo "RELEASE_BRANCH=$RELEASE_BRANCH" >> $GITHUB_ENV

  deploy-prod:
    name: Deploy to Production
    runs-on: ubuntu-latest
    needs: create-release-branch

    steps:
    - uses: actions/checkout@v4
      with:
        ref: ${{ env.RELEASE_BRANCH }}
        fetch-depth: 0

    - name: Tag release before deployment
      run: |
        SHORT_SHA=$(git rev-parse --short HEAD)
        DATE=$(date +'%d%m%Y')
        VERSION_TAG="prod-${DATE}-${SHORT_SHA}"

        echo "VERSION_TAG=$VERSION_TAG" >> $GITHUB_ENV
        git config --global user.email "ci-bot@github.com"
        git config --global user.name "CI Bot"
        git tag $VERSION_TAG
        git push origin $VERSION_TAG

    - name: Deploy to PROD
      run: echo "Deploying $VERSION_TAG to production..."

  test-prod-sanity:
    name: Smoke Tests
    runs-on: ubuntu-latest
    needs: deploy-prod

    steps:
    - uses: actions/checkout@v4
    
    - uses: actions/setup-node@v4
      with:
        node-version: '20.x'
    
    - run: npm install
    
    - name: Start prod server
      run: |
        node server.js &
        sleep 3
    
    - name: Run prod health check
      run: |
        chmod +x __tests__/sanity.sh
        __tests__/sanity.sh
    
    - name: Stop prod server
      run: pkill -f "node server.js" || true

  tag-prod:
    name: Update prod-stable
    runs-on: ubuntu-latest
    needs: test-prod-sanity
    if: ${{ needs.test-prod-sanity.result == 'success' }}

    steps:
    - uses: actions/checkout@v4
      with:
        fetch-depth: 0

    - name: Move prod-stable tag
      run: |
        git config --global user.email "ci-bot@github.com"
        git config --global user.name "CI Bot"
        git tag -f prod-stable ${{ env.VERSION_TAG }}
        git push origin -f prod-stable

  merge-to-main:
    name: Merge Release to Main
    runs-on: ubuntu-latest
    needs: tag-prod

    steps:
    - uses: actions/checkout@v4
      with:
        ref: ${{ env.RELEASE_BRANCH }}
        fetch-depth: 0

    - name: Merge release branch to main
      run: |
        git checkout main
        git merge ${{ env.RELEASE_BRANCH }} --no-ff
        git push origin main
