name: Unit Tests & Static Analysis

on:
  push:
    branches:
      - 'feature/**'
      - 'bugfix/**'

permissions:
  contents: read

jobs:
  eslint:
    name: ESLint
    runs-on: ubuntu-latest
    continue-on-error: true
    
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-node@v4
      with:
        node-version: '20.x'
    - name: Install ESLint
      run: |
        npm install --save-dev eslint
        npx eslint .

  prettier:
    name: Prettier
    runs-on: ubuntu-latest
    continue-on-error: true
    
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-node@v4
      with:
        node-version: '20.x'
    - name: Install Prettier
      run: |
        npm install --save-dev prettier
        npx prettier --check .

  unit-tests:
    name: Unit Tests
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-node@v4
      with:
        node-version: '20.x'
    - name: Install Dependencies
      run: npm install
    - name: Run Tests
      run: npm test
    - name: Upload Test Results
      if: always()
      uses: actions/upload-artifact@v4
      with:
        name: unit-test-results
        path: test-results/junit.xml
    - name: Publish Test Results to GitHub UI
      uses: EnricoMi/publish-unit-test-result-action@v2
      if: always()
      with:
        files: test-results/junit.xml

  snyk-security:
    name: Snyk Security Scan
    runs-on: ubuntu-latest
    continue-on-error: true
    
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-node@v4
      with:
        node-version: '20.x'
    - name: Install Dependencies
      run: npm install
    - name: Run Snyk
      uses: snyk/actions/node@v1
      env:
        SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
